package com.stockiq.trading.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Order entity representing a trading order
 * Maps to the 'orders' table in Postgres
 */
@Entity
@Table(name = "orders")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Order {

    /**
     * Primary key - UUID generated by database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Foreign key to users table
     * ON DELETE CASCADE means if user is deleted, their orders are too
     */
    @Column(name = "user_id", nullable = false)
    private UUID userId;

    /**
     * Trading symbol (e.g., "AAPL", "BTCUSD")
     * Max 32 characters
     */
    @Column(name = "symbol", nullable = false, length = 32)
    private String symbol;

    /**
     * Order side: BUY or SELL
     * Stored as STRING in database (Postgres ENUM)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "side", nullable = false, columnDefinition = "order_side")
    private OrderSide side;

    /**
     * Order type: MARKET or LIMIT
     * Stored as STRING in database (Postgres ENUM)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, columnDefinition = "order_type")
    private OrderType type;

    /**
     * Limit price (null for MARKET orders)
     * NUMERIC(18,8) allows large numbers with 8 decimal precision
     */
    @Column(name = "price", precision = 18, scale = 8)
    private BigDecimal price;

    /**
     * Order quantity
     * Must be positive, non-null
     */
    @Column(name = "quantity", nullable = false, precision = 18, scale = 8)
    private BigDecimal quantity;

    /**
     * Filled quantity (how much has been executed)
     * Starts at 0, increases as order fills
     */
    @Column(name = "filled_qty", nullable = false, precision = 18, scale = 8)
    @Builder.Default
    private BigDecimal filledQty = BigDecimal.ZERO;

    /**
     * Order status: NEW, PARTIALLY_FILLED, FILLED, CANCELLED, REJECTED
     * Stored as STRING in database (Postgres ENUM)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, columnDefinition = "order_status")
    @Builder.Default
    private OrderStatus status = OrderStatus.NEW;

    /**
     * When the order was created
     * TIMESTAMPTZ preserves timezone info
     */
    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    /**
     * When the order was last updated
     * Should be updated on every status change
     */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * JPA lifecycle callback: set timestamps before persisting
     */
    @PrePersist
    protected void onCreate() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * JPA lifecycle callback: update timestamp before updating
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
